### ISSUE TITLE
Werte sind nicht aktuell

### ISSUE THREAD

**Issue by schmupu** [TA2k/ioBroker.withings#1]
**Describe the bug**  
Erst einmal Danke für den Adapter! Finde ich megamäßig gut!

Ich hatte die Version 0.0.1 installiert. Da wurden die Werte (Gewicht und Fettanteil) richtig angezeigt und die Werte in den Objekten erfuhren nur ein Update wenn mann sich gewogen hat. Jetzt in Version 0.0.3 findet ein update alle paar Minuten statt (abhg. von der Polltime). Der Wert in den Objekte bleibt aber gleich. Das ist aber halb so schlimm.
Das Gewicht  in `withings.0.xxxxxxx.measures.measuregrps01.1.value` wird nach dem Wiegen in der Version 0.0.3 nicht mehr aktualisiert.  In der Version 0.0.1 hat es noch wunderbar funktioniert. 

Wenn man sich jeden Tag wiegen würde, werden in der Version 0.0.1 die Werte wie folgt geändert / erneuert:

| Objekt  Gewicht    	| Zeitpunkt Änderung	| 
|-----------------	|--------------	|
| withings.0.xxxxxxx.measures.measuregrps01.1.value 	|     heute     	| 
| withings.0.xxxxxxx.measures.measuregrps02.1.value 	|     gestern       	| 
| withings.0.xxxxxxx.measures.measuregrps031.value 	|     vorgestern      	| 

In der Version 0.0.3 kann ich nicht sagen wo ich das aktuelle Gewicht finde. In der Version 0.0.1 war der aktuelle Wert immer in `withings.0.xxxxxxx.measures.measuregrps01.1.value`  zu finden.

**To Reproduce**  
2 Tage hintereinander wiegen und Werte in `withings.0.xxxxxxx.measures.measuregrps01.1.value` und `withings.0.xxxxxxx.measures.measuregrps02.1.value` anschauen. Auch die Werte in `withings.0.xxxxxxx.measures.measuregrps01.date` und `withings.0.xxxxxxx.measures.measuregrps02.date` müssten einen Tag unterschied dann zeigen. 

**Expected behavior**  
siehe oben

**Screenshots & Logfiles**  
keine

**Versions:**  
 - Adapter version: 0.0.3
 - JS-Controller version: 3.3.22
 - Node version: 14
 - Operating system: Linux / Ubuntu

**Additional context**  
keine

**Comment by TA2k** [comment]
Eigentlich gab es zwischen den version keine änderung nur das die datenpunkte unter die benutzer id geschoben wurden

**Comment by TA2k** [comment]
Deine Aussage ist also das die datenpunkte nicht nach date sortiert sind?

**Comment by schmupu** [comment]
> Deine Aussage ist also das die datenpunkte nicht nach date sortiert sind?

Ja, das könnte gut sein. Mir kommt so vor, dass der aktuelle Wet in measure02 abgelegt ist und der alte Wert unter measure 01. Nur das Date und Create Date sind auch vom aktuellen Wert in measure01.
Inn der Version 0.0.1 stimmte die Werte alle

**Comment by schmupu** [comment]
Ich habe es jetzt 2 Tage verfolgt und es sieht momentan gut aus. Vielleicht lag es an der Umstellung von Version 0.0.1 auf 0.0.3 . Ich werde das Issue schließen. Tritt der Fehler nochmals auf, dann melde ich mich. 
Danke für Alles !!!!
