### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by Merexor** [TA2k/ioBroker.withings#3]
Hallo,

Hab heute ein email erhalten das die API ab 8.2.2022 abgeschaltet wird. Wollte nur Informationen weiterleiten. 

![image](https://user-images.githubusercontent.com/68726324/151785015-a31af8bb-7763-40d3-bdf0-b4dd0817fbbf.jpeg)

[Link](https://support.withings.com/hc/en-us/articles/360016745358--BREAKING-Shutting-down-access-and-refresh-tokens-endpoints)

**Comment by TA2k** [comment]
Der Adapter nutzt bereits die neue api
