### ISSUE TITLE
After a restart of the Adapter i get no connection anymore.

### ISSUE THREAD

**Issue by 6RomN6** [TA2k/ioBroker.withings#4]
Thanks for this addapter!!!

After a restart of the Adapter i get no connection anymore.

Log Files shows following:

withings.0 | 2022-01-31 13:43:53.859 | error | {"status":503,"error":"Invalid Params: Missing [refresh_token]"} -- | -- | -- | --

withings.0 | 2022-01-31 13:43:53.731 | warn | Please check username and password

withings.0 | 2022-01-31 13:43:52.893 | info | starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.withings, node: v14.18.2, js-controller: 3.3.22

withings.0 | 2022-01-31 13:43:50.015 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

withings.0 | 2022-01-31 13:43:50.014 | info | terminating

withings.0 | 2022-01-31 13:43:50.014 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by 6RomN6** [comment]
My bad, i found my error. Sorry for that

**Comment by jroegner** [comment]
> My bad, i found my error. Sorry for that

Hi, would you describe what your error was? I have the same issue and cannot find the reason.
