### ISSUE TITLE
Es erfolgt kein  Adapter Login mehr

### ISSUE THREAD

**Issue by Menne01** [TA2k/ioBroker.withings#7]
Hallo,
die Berichte häufen sich im Thread, das es nun vermehrt zu Login Problemen kommt.
Das ist auch bei mit jetzt der Fall.

Auch ein Update auf Node.js 14.19.1 bringt keine Lösung.

`<html><body>

withings.0 | 2022-04-16 13:46:36.289 | error | {"status":503,"error":"Invalid Params: Missing [refresh_token]"}
-- | -- | -- | --
withings.0 | 2022-04-16 13:46:36.288 | debug | {"status":503,"error":"Invalid Params: Missing [refresh_token]"}
withings.0 | 2022-04-16 13:46:36.132 | warn | Please check username and password
withings.0 | 2022-04-16 13:46:36.132 | debug | undefined
withings.0 | 2022-04-16 13:46:36.131 | debug | /new_workflow/login?r=https%3A%2F%2Faccount.withings.com%2Foauth2_user%2Faccount_login%3Fresponse_type%3Dcode%26client_id%3D76990f68adf289700738e24d704d06d7ce2149cd233a3663ae00cc867c864c4f%26state%3Dh4fhjnc2daoc3m%26scope%3Duser.activity%2Cuser.metrics%2Cuser.info%26redirect_uri%3Dhttp%3A%2F%2Flocalhost%26b%3Dauthorize2

</body>
</html>`

**Comment by TA2k** [comment]
Fixed with 0.0.7
